//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public long ApplicationId { get; set; }
        public Nullable<long> UserId { get; set; }
        public System.DateTime TodayDate { get; set; }
        public string EmailManager { get; set; }
        public string PositionHired { get; set; }
        public System.DateTime StartDate { get; set; }
        public string AditionalServices { get; set; }
        public string AccessLevel { get; set; }
        public string AditionalInformation { get; set; }
        public string Building { get; set; }
        public string RestrictedAccess { get; set; }
        public string Services { get; set; }
        public string CompanyName { get; set; }
        public string FullName { get; set; }
    
        public virtual Applicant Applicant { get; set; }
    }
}
